@SMS.Api_HostAddress = http://localhost:5032

### Health
GET {{SMS.Api_HostAddress}}/health
Accept: application/json

### Bootstrap
GET {{SMS.Api_HostAddress}}/api/bootstrap
Accept: application/json

### Admin Login
POST {{SMS.Api_HostAddress}}/api/auth/admin/login
Content-Type: application/json

{
  "usernameOrEmail": "admin",
  "password": "Admin@123"
}
